/**
 * Produces two standalone SQL files for the Supabase SQL Editor:
 *
 *   supabase/dist/01_schema.sql  — enums, tables, indexes, FKs, RLS, triggers
 *   supabase/dist/02_seed.sql    — auth users, exercise library, demo fixture
 *
 * Why this exists: `drizzle-kit generate` ignores `schemaFilter` (that setting
 * only affects push/introspect), so it emits `CREATE SCHEMA "auth"` and its own
 * `auth.users` table — which would collide with the real ones on Supabase — and
 * it drops the `public.users.id -> auth.users.id` foreign key entirely. This
 * script fixes both, then appends the hand-written RLS migration.
 *
 * The seed is dumped from the local database rather than re-derived, so what
 * ships is exactly what `npm run db:seed` produces and the RLS tests ran green
 * against. Values are rendered with Postgres' own `quote_nullable(col::text)`,
 * and string literals coerce to uuid/enum/array/timestamp on insert.
 *
 * Run: npx tsx scripts/build-supabase-sql.ts
 */

import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import postgres from "postgres";

const OUT_DIR = path.join(process.cwd(), "supabase", "dist");
const DDL_FILE = path.join(process.cwd(), "drizzle", "0000_heme_schema.sql");
const RLS_FILE = path.join(
  process.cwd(),
  "supabase",
  "migrations",
  "0001_tenancy_rls.sql",
);

/** Parent-before-child, so the file can run without deferring constraints. */
const TABLE_ORDER = [
  "organizations",
  "users",
  "exercises",
  "athletes",
  "groups",
  "group_members",
  "athlete_maxes",
  "programs",
  "program_blocks",
  "microcycles",
  "sessions",
  "session_blocks",
  "exercise_slots",
  "prescribed_sets",
  "program_assignments",
  "logged_sessions",
  "logged_sets",
] as const;

/** Self-referencing columns, deferred to an UPDATE pass after the inserts. */
const SELF_REFS: Record<string, string[]> = {
  exercises: ["derived_from_exercise_id", "progression_of_id"],
};

const SEED_PASSWORD = "heme-demo-1234";

/** Rows per INSERT statement. Keeps individual statements small enough to split. */
const ROWS_PER_INSERT = 50;

/* ------------------------------------------------------------------ *
 * Block 1 — schema
 * ------------------------------------------------------------------ */

async function buildSchema(): Promise<string> {
  let ddl = await readFile(DDL_FILE, "utf8");

  // Supabase owns the auth schema. Drop drizzle's attempts to recreate it.
  ddl = ddl.replace(/CREATE SCHEMA "auth";\s*(-->\s*statement-breakpoint)?\s*/g, "");
  ddl = ddl.replace(
    /CREATE TABLE "auth"\."users" \([\s\S]*?\);\s*(-->\s*statement-breakpoint)?\s*/g,
    "",
  );
  // drizzle-kit's statement separator is meaningless in a plain SQL file.
  ddl = ddl.replace(/-->\s*statement-breakpoint/g, "");
  ddl = ddl.replace(/\n{3,}/g, "\n\n").trim();

  const rls = (await readFile(RLS_FILE, "utf8"))
    // The RLS file wraps itself in begin/commit; the combined file has its own.
    .replace(/^begin;\s*/m, "")
    .replace(/\s*commit;\s*$/m, "")
    .trim();

  return `-- ===================================================================
-- HEME — Block 1 of 2: schema, row level security, triggers
--
-- Paste into the Supabase SQL Editor and run. Safe on a fresh project.
-- Run Block 2 (02_seed.sql) afterwards.
--
-- Creates 21 enums, 17 tables, their indexes and foreign keys, then the
-- isolation layer: helper functions, the signup trigger, the tenancy
-- inheritance triggers, and RLS policies on every table.
--
-- Isolation model: an organisation is the tenant boundary; inside it a coach
-- sees only rows they own (athletes, groups, programs carry owner_coach_id).
-- Everything else inherits visibility through one denormalised column, so no
-- policy walks more than one join.
-- ===================================================================

begin;

-- pgcrypto backs gen_random_uuid() and the bcrypt hashing used in Block 2.
create extension if not exists pgcrypto with schema extensions;

-- ===================================================================
-- 1. Tables, enums, indexes, foreign keys  (generated by drizzle-kit)
-- ===================================================================

${ddl}

-- The link Drizzle cannot express here: a coach profile IS an auth user.
-- Same UUID, cascade on delete, so identity and profile can never drift.
alter table "public"."users"
  drop constraint if exists "users_id_auth_users_id_fk";
alter table "public"."users"
  add constraint "users_id_auth_users_id_fk"
  foreign key ("id") references "auth"."users"("id") on delete cascade;

-- ===================================================================
-- 2. Isolation layer  (functions, triggers, policies)
-- ===================================================================

${rls}

commit;

-- Expect: 17 tables with RLS enabled AND forced, 27 policies, 11 triggers.
select
  (select count(*) from pg_class c join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relrowsecurity and c.relforcerowsecurity) as rls_tables,
  (select count(*) from pg_policies where schemaname = 'public') as policies,
  (select count(*) from pg_trigger
    where tgname = 'inherit_tenancy_trg' and not tgisinternal) as inherit_triggers;
`;
}

/* ------------------------------------------------------------------ *
 * Block 2 — seed
 * ------------------------------------------------------------------ */

interface CoachRow {
  id: string;
  email: string;
  name: string;
}

async function buildSeed(sql: postgres.Sql): Promise<string> {
  const parts: string[] = [];

  const coaches = await sql<CoachRow[]>`
    select id, email, name from public.users order by email
  `;

  parts.push(`-- ===================================================================
-- HEME — Block 2 of 2: seed data
--
-- Run AFTER Block 1. Creates three coach logins, the 213-exercise global
-- library, a demo roster, and five program templates.
--
-- Fixture shape — deliberately adversarial, so isolation is observable:
--   Org A "HEME Performance"  ── Alex Reid  (Priya, Marcus)
--                             └─ Jordan Six (Aisha)     <- same org, other coach
--   Org B "Northside Strength" ── Sam Okafor (Tom)       <- separate tenant
--
-- Sign in as Alex then Jordan: same organisation, and the athlete lists do
-- not overlap. That is the whole point of the RLS layer.
--
-- Logins (all password: ${SEED_PASSWORD}):
${coaches.map((c) => `--   ${c.email.padEnd(16)} ${c.name}`).join("\n")}
-- ===================================================================

begin;

-- ===================================================================
-- 1. Auth identities
--
-- Inserted directly because the Admin API is not being used here. The
-- password is bcrypt-hashed with pgcrypto, and an auth.identities row is
-- added because GoTrue requires one for email/password sign-in.
-- ===================================================================

insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password,
  email_confirmed_at, created_at, updated_at,
  raw_app_meta_data, raw_user_meta_data, is_sso_user, is_anonymous
) values`);

  const authRows = coaches.map((c) => {
    const meta = JSON.stringify({
      name: c.name,
      // Reconstructed below from the organisation the coach actually belongs to.
      org_name: null,
    });
    return `  ('00000000-0000-0000-0000-000000000000', ${lit(c.id)}, 'authenticated', 'authenticated',
   ${lit(c.email)}, extensions.crypt(${lit(SEED_PASSWORD)}, extensions.gen_salt('bf')),
   now(), now(), now(),
   '{"provider":"email","providers":["email"]}'::jsonb, ${lit(meta)}::jsonb, false, false)`;
  });
  parts.push(authRows.join(",\n") + "\non conflict (id) do nothing;\n");

  parts.push(`insert into auth.identities (
  id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at
) values`);
  parts.push(
    coaches
      .map(
        (c) =>
          `  (extensions.gen_random_uuid(), ${lit(c.id)}, ${lit(c.id)},
   jsonb_build_object('sub', ${lit(c.id)}, 'email', ${lit(c.email)}, 'email_verified', true, 'phone_verified', false),
   'email', now(), now(), now())`,
      )
      .join(",\n") + "\non conflict do nothing;\n",
  );

  parts.push(`-- The signup trigger just created one organisation and profile per coach.
-- Clear them: the rows below carry fixed ids that the rest of the seed
-- references, and the two coaches in Org A must share one organisation.
delete from public.users;
delete from public.organizations;
`);

  parts.push(`-- ===================================================================
-- 2. Reference and fixture data
-- ===================================================================
`);

  for (const table of TABLE_ORDER) {
    const cols = await columnsOf(sql, table);
    const deferred = SELF_REFS[table] ?? [];
    const insertCols = cols.filter((c) => !deferred.includes(c));

    const rows = await sql.unsafe<{ v: string }[]>(
      `select '(' || ${insertCols
        .map((c) => `coalesce(quote_nullable(${quoteIdent(c)}::text), 'NULL')`)
        .join(" || ',' || ")} || ')' as v
       from public.${quoteIdent(table)}
       order by 1`,
    );

    if (rows.length === 0) {
      parts.push(`-- ${table}: no rows\n`);
      continue;
    }

    // Emitted as several bounded INSERTs rather than one enormous VALUES list,
    // so the file can be split for the SQL Editor and a failure points at a
    // small statement instead of a 500 KB one.
    const colList = insertCols.map(quoteIdent).join(", ");
    const statements = chunk(
      rows.map((r) => `  ${r.v}`),
      ROWS_PER_INSERT,
    ).map(
      (group) =>
        `insert into public.${quoteIdent(table)} (${colList}) values\n${group};`,
    );

    parts.push(
      `-- ${table} (${rows.length} ${rows.length === 1 ? "row" : "rows"})\n` +
        statements.join("\n") +
        "\n",
    );

    // Second pass for columns that point at a later row in the same table.
    if (deferred.length) {
      const updates = await sql.unsafe<{ v: string }[]>(
        `select 'update public.${table} set ' ||
                ${deferred
                  .map(
                    (d) =>
                      `'${d} = ' || coalesce(quote_nullable(${quoteIdent(d)}::text), 'NULL')`,
                  )
                  .join(" || ', ' || ")}
                || ' where id = ' || quote_literal(id::text) || ';' as v
         from public.${quoteIdent(table)}
         where ${deferred.map((d) => `${quoteIdent(d)} is not null`).join(" or ")}
         order by 1`,
      );
      if (updates.length) {
        parts.push(
          `-- ${table}: self-references, applied once every row exists\n` +
            updates.map((u) => u.v).join("\n") +
            "\n",
        );
      }
    }
  }

  parts.push(`commit;

-- ===================================================================
-- Verification
-- ===================================================================

-- Expect: 213 global exercises, 3 coaches, 2 organisations, 4 athletes,
-- 6 programs, 915 prescribed sets.
select
  (select count(*) from public.exercises where org_id is null) as global_exercises,
  (select count(*) from public.users)                          as coaches,
  (select count(*) from public.organizations)                  as organizations,
  (select count(*) from public.athletes)                        as athletes,
  (select count(*) from public.programs)                       as programs,
  (select count(*) from public.prescribed_sets)                as prescribed_sets;

-- The isolation check. Expect exactly one row per coach, and note that the
-- two "HEME Performance" coaches own different athletes.
select u.email, o.name as organisation, count(a.id) as own_athletes,
       string_agg(a.first_name || ' ' || a.last_name, ', ' order by a.first_name) as roster
from public.users u
join public.organizations o on o.id = u.org_id
left join public.athletes a on a.owner_coach_id = u.id
group by u.email, o.name
order by o.name, u.email;
`);

  return parts.join("\n");
}

/* ------------------------------------------------------------------ *
 * Helpers
 * ------------------------------------------------------------------ */

function quoteIdent(name: string): string {
  return `"${name.replace(/"/g, '""')}"`;
}

function lit(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

/** Groups row literals into bounded VALUES lists, one per INSERT statement. */
function chunk(lines: string[], size: number): string[] {
  const out: string[] = [];
  for (let i = 0; i < lines.length; i += size) {
    out.push(lines.slice(i, i + size).join(",\n"));
  }
  return out;
}

async function columnsOf(sql: postgres.Sql, table: string): Promise<string[]> {
  const rows = await sql<{ column_name: string }[]>`
    select column_name
    from information_schema.columns
    where table_schema = 'public' and table_name = ${table}
    order by ordinal_position
  `;
  return rows.map((r) => r.column_name);
}

/* ------------------------------------------------------------------ *
 * Main
 * ------------------------------------------------------------------ */

async function main() {
  const sql = postgres(
    process.env.DATABASE_URL ??
      "postgresql://postgres:postgres@localhost:5432/heme",
    { max: 1 },
  );

  try {
    await mkdir(OUT_DIR, { recursive: true });

    const schema = await buildSchema();
    await writeFile(path.join(OUT_DIR, "01_schema.sql"), schema);
    console.log(
      `  · 01_schema.sql  ${(schema.length / 1024).toFixed(0)} KB`,
    );

    const seed = await buildSeed(sql);
    await writeFile(path.join(OUT_DIR, "02_seed.sql"), seed);
    console.log(`  · 02_seed.sql    ${(seed.length / 1024).toFixed(0)} KB`);
  } finally {
    await sql.end();
  }
}

main().catch((err) => {
  console.error("Build failed:", err);
  process.exit(1);
});
