/**
 * The global exercise library.
 *
 * Every entry is tagged across the full taxonomy so the builder's filters,
 * the prescription UI, and later volume-by-pattern reporting all work off the
 * same data. `metrics` is the important one: it decides which inputs render,
 * so a plank never shows a weight box.
 */

import type {
  Equipment,
  Muscle,
  TrackedMetric,
} from "@/lib/db/schema/enums";

type Pattern =
  | "squat"
  | "hinge"
  | "lunge"
  | "vertical_push"
  | "horizontal_push"
  | "vertical_pull"
  | "horizontal_pull"
  | "carry"
  | "rotation"
  | "anti_rotation"
  | "anti_extension"
  | "anti_lateral_flexion"
  | "gait"
  | "jump_land"
  | "throw"
  | "sprint"
  | "olympic"
  | "isolation"
  | "mobility";

type Category =
  | "main_lift"
  | "accessory"
  | "corrective"
  | "plyometric"
  | "conditioning"
  | "mobility"
  | "warmup"
  | "skill";

type Laterality = "bilateral" | "unilateral" | "alternating";
type ForceVector = "vertical" | "horizontal" | "lateral" | "rotational";
type Contraction =
  | "concentric"
  | "eccentric"
  | "isometric"
  | "ballistic"
  | "mixed";
type LoadBasis =
  | "own_1rm"
  | "derived_from_exercise"
  | "bodyweight"
  | "absolute_only";

export interface SeedExercise {
  name: string;
  pattern: Pattern;
  category: Category;
  equipment: Equipment[];
  primary: Muscle[];
  secondary?: Muscle[];
  laterality?: Laterality;
  vector?: ForceVector;
  contraction?: Contraction;
  metrics?: TrackedMetric[];
  loadBasis?: LoadBasis;
  /** Slug of the lift whose max this one is programmed from. */
  derivedFrom?: string;
  derivedRatio?: number;
  maxTestable?: boolean;
  difficulty?: number;
  /** Slug of the easier variant this exercise progresses from. */
  progressionOf?: string;
  cues?: string[];
  aliases?: string[];
  tempo?: string;
  rest?: number;
  tags?: string[];
}

/* --------------------------- metric presets --------------------------- */

/** Main barbell lifts: velocity is meaningful, so VBT fields render. */
const STRENGTH: TrackedMetric[] = ["load", "reps", "rpe", "tempo", "velocity"];
/** General resistance work. */
const RESIST: TrackedMetric[] = ["load", "reps", "rpe", "tempo"];
/** Bodyweight movements that can be loaded. */
const BW: TrackedMetric[] = ["reps", "load", "rpe", "tempo"];
const TIMED: TrackedMetric[] = ["time", "rpe"];
const JUMP_H: TrackedMetric[] = ["reps", "height", "rpe"];
const JUMP_D: TrackedMetric[] = ["reps", "distance", "rpe"];
const THROWN: TrackedMetric[] = ["reps", "distance", "load", "rpe"];
const SLED: TrackedMetric[] = ["load", "distance", "time", "rpe"];
const RUN: TrackedMetric[] = ["distance", "time", "rpe", "heart_rate"];
const CONDI: TrackedMetric[] = [
  "time",
  "distance",
  "calories",
  "heart_rate",
  "rpe",
];
const MOBI: TrackedMetric[] = ["reps", "time"];

export const EXERCISE_LIBRARY: SeedExercise[] = [
  /* ============================== SQUAT ============================== */
  {
    name: "Back Squat",
    aliases: ["High Bar Squat", "Barbell Squat"],
    pattern: "squat",
    category: "main_lift",
    equipment: ["barbell", "rack"],
    primary: ["quads", "glutes"],
    secondary: ["erectors", "adductors", "hamstrings"],
    vector: "vertical",
    metrics: STRENGTH,
    loadBasis: "own_1rm",
    maxTestable: true,
    difficulty: 4,
    cues: ["Big breath into the belt", "Knees track over toes", "Drive the floor away"],
    rest: 180,
    tags: ["compound", "lower_body", "test_lift"],
  },
  {
    name: "Front Squat",
    pattern: "squat",
    category: "main_lift",
    equipment: ["barbell", "rack"],
    primary: ["quads"],
    secondary: ["glutes", "erectors", "abs"],
    vector: "vertical",
    metrics: STRENGTH,
    loadBasis: "derived_from_exercise",
    derivedFrom: "back-squat",
    derivedRatio: 0.85,
    maxTestable: true,
    difficulty: 4,
    cues: ["Elbows high", "Upright torso", "Rack tight on the delts"],
    rest: 180,
    tags: ["compound", "lower_body"],
  },
  {
    name: "Box Squat",
    pattern: "squat",
    category: "main_lift",
    equipment: ["barbell", "box", "rack"],
    primary: ["quads", "glutes"],
    secondary: ["hamstrings", "erectors"],
    vector: "vertical",
    metrics: STRENGTH,
    loadBasis: "derived_from_exercise",
    derivedFrom: "back-squat",
    derivedRatio: 0.9,
    difficulty: 3,
    cues: ["Sit back, not down", "Stay tight on the box", "Explode off"],
    rest: 180,
    tags: ["compound", "conjugate"],
  },
  {
    name: "Safety Bar Squat",
    pattern: "squat",
    category: "main_lift",
    equipment: ["safety_squat_bar", "rack"],
    primary: ["quads", "glutes"],
    secondary: ["erectors"],
    vector: "vertical",
    metrics: STRENGTH,
    loadBasis: "derived_from_exercise",
    derivedFrom: "back-squat",
    derivedRatio: 0.9,
    difficulty: 3,
    tags: ["compound", "shoulder_friendly"],
  },
  {
    name: "Goblet Squat",
    pattern: "squat",
    category: "accessory",
    equipment: ["dumbbell", "kettlebell"],
    primary: ["quads", "glutes"],
    secondary: ["abs"],
    vector: "vertical",
    metrics: RESIST,
    difficulty: 2,
    progressionOf: "air-squat",
    cues: ["Elbows inside the knees", "Chest tall"],
    rest: 90,
    tags: ["beginner_friendly"],
  },
  {
    name: "Overhead Squat",
    pattern: "squat",
    category: "skill",
    equipment: ["barbell"],
    primary: ["quads", "glutes"],
    secondary: ["front_delts", "abs", "traps"],
    vector: "vertical",
    metrics: STRENGTH,
    loadBasis: "derived_from_exercise",
    derivedFrom: "back-squat",
    derivedRatio: 0.6,
    difficulty: 5,
    cues: ["Push up into the bar", "Bar over mid-foot"],
    tags: ["weightlifting", "mobility_demand"],
  },
  {
    name: "Zercher Squat",
    pattern: "squat",
    category: "accessory",
    equipment: ["barbell"],
    primary: ["quads", "glutes"],
    secondary: ["erectors", "abs", "biceps"],
    vector: "vertical",
    metrics: RESIST,
    difficulty: 4,
    tags: ["strongman"],
  },
  {
    name: "Hack Squat",
    pattern: "squat",
    category: "accessory",
    equipment: ["machine"],
    primary: ["quads"],
    secondary: ["glutes"],
    vector: "vertical",
    metrics: RESIST,
    difficulty: 2,
    rest: 120,
    tags: ["hypertrophy"],
  },
  {
    name: "Leg Press",
    pattern: "squat",
    category: "accessory",
    equipment: ["machine"],
    primary: ["quads", "glutes"],
    secondary: ["hamstrings"],
    vector: "vertical",
    metrics: RESIST,
    difficulty: 1,
    rest: 120,
    tags: ["hypertrophy", "rehab_friendly"],
  },
  {
    name: "Split Squat",
    pattern: "squat",
    category: "accessory",
    equipment: ["dumbbell", "barbell"],
    primary: ["quads", "glutes"],
    secondary: ["adductors"],
    laterality: "unilateral",
    vector: "vertical",
    metrics: RESIST,
    difficulty: 2,
    rest: 90,
    tags: ["unilateral"],
  },
  {
    name: "Bulgarian Split Squat",
    aliases: ["Rear Foot Elevated Split Squat", "RFESS"],
    pattern: "squat",
    category: "accessory",
    equipment: ["dumbbell", "bench"],
    primary: ["quads", "glutes"],
    secondary: ["adductors", "hamstrings"],
    laterality: "unilateral",
    vector: "vertical",
    metrics: RESIST,
    difficulty: 3,
    progressionOf: "split-squat",
    cues: ["Front shin vertical", "Trail knee under the hip"],
    rest: 90,
    tags: ["unilateral"],
  },
  {
    name: "Pause Squat",
    pattern: "squat",
    category: "main_lift",
    equipment: ["barbell", "rack"],
    primary: ["quads", "glutes"],
    vector: "vertical",
    contraction: "isometric",
    metrics: STRENGTH,
    loadBasis: "derived_from_exercise",
    derivedFrom: "back-squat",
    derivedRatio: 0.85,
    difficulty: 4,
    tempo: "3-3-X-0",
    tags: ["compound", "positional_strength"],
  },
  {
    name: "Belt Squat",
    pattern: "squat",
    category: "accessory",
    equipment: ["machine"],
    primary: ["quads", "glutes"],
    vector: "vertical",
    metrics: RESIST,
    difficulty: 2,
    tags: ["spine_sparing"],
  },
  {
    name: "Pin Squat",
    pattern: "squat",
    category: "accessory",
    equipment: ["barbell", "rack"],
    primary: ["quads", "glutes"],
    vector: "vertical",
    contraction: "concentric",
    metrics: STRENGTH,
    difficulty: 4,
    tags: ["conjugate", "positional_strength"],
  },
  {
    name: "Air Squat",
    pattern: "squat",
    category: "warmup",
    equipment: ["bodyweight"],
    primary: ["quads", "glutes"],
    vector: "vertical",
    metrics: BW,
    loadBasis: "bodyweight",
    difficulty: 1,
    tags: ["beginner_friendly"],
  },
  {
    name: "Wall Sit",
    pattern: "squat",
    category: "accessory",
    equipment: ["bodyweight"],
    primary: ["quads"],
    vector: "vertical",
    contraction: "isometric",
    metrics: TIMED,
    loadBasis: "bodyweight",
    difficulty: 1,
    tags: ["isometric"],
  },
  {
    name: "Cossack Squat",
    pattern: "squat",
    category: "mobility",
    equipment: ["bodyweight", "kettlebell"],
    primary: ["adductors", "quads"],
    secondary: ["glutes"],
    laterality: "alternating",
    vector: "lateral",
    metrics: RESIST,
    difficulty: 3,
    tags: ["mobility", "frontal_plane"],
  },
  {
    name: "Landmine Squat",
    pattern: "squat",
    category: "accessory",
    equipment: ["landmine", "barbell"],
    primary: ["quads", "glutes"],
    vector: "vertical",
    metrics: RESIST,
    difficulty: 2,
    tags: ["beginner_friendly"],
  },
  {
    name: "Sissy Squat",
    pattern: "squat",
    category: "accessory",
    equipment: ["bodyweight"],
    primary: ["quads"],
    vector: "vertical",
    metrics: BW,
    loadBasis: "bodyweight",
    difficulty: 4,
    tags: ["knee_dominant"],
  },

  /* ============================== HINGE ============================== */
  {
    name: "Deadlift",
    aliases: ["Conventional Deadlift"],
    pattern: "hinge",
    category: "main_lift",
    equipment: ["barbell"],
    primary: ["glutes", "hamstrings", "erectors"],
    secondary: ["traps", "lats", "forearms"],
    vector: "vertical",
    metrics: STRENGTH,
    loadBasis: "own_1rm",
    maxTestable: true,
    difficulty: 4,
    cues: ["Wedge into the bar", "Lats tight", "Push the floor away"],
    rest: 240,
    tags: ["compound", "posterior_chain", "test_lift"],
  },
  {
    name: "Sumo Deadlift",
    pattern: "hinge",
    category: "main_lift",
    equipment: ["barbell"],
    primary: ["glutes", "quads", "adductors"],
    secondary: ["erectors", "traps"],
    vector: "vertical",
    metrics: STRENGTH,
    loadBasis: "own_1rm",
    maxTestable: true,
    difficulty: 4,
    rest: 240,
    tags: ["compound", "posterior_chain"],
  },
  {
    name: "Trap Bar Deadlift",
    aliases: ["Hex Bar Deadlift"],
    pattern: "hinge",
    category: "main_lift",
    equipment: ["trap_bar"],
    primary: ["glutes", "quads", "hamstrings"],
    secondary: ["erectors", "traps"],
    vector: "vertical",
    metrics: STRENGTH,
    loadBasis: "own_1rm",
    maxTestable: true,
    difficulty: 3,
    cues: ["Hips between squat and deadlift height", "Chest proud"],
    rest: 180,
    tags: ["compound", "athlete_friendly"],
  },
  {
    name: "Romanian Deadlift",
    aliases: ["RDL"],
    pattern: "hinge",
    category: "accessory",
    equipment: ["barbell", "dumbbell"],
    primary: ["hamstrings", "glutes"],
    secondary: ["erectors"],
    vector: "vertical",
    contraction: "eccentric",
    metrics: RESIST,
    loadBasis: "derived_from_exercise",
    derivedFrom: "deadlift",
    derivedRatio: 0.7,
    difficulty: 3,
    cues: ["Push the hips back", "Soft knees", "Bar stays on the thigh"],
    tempo: "3-1-1-0",
    rest: 120,
    tags: ["posterior_chain", "hamstring"],
  },
  {
    name: "Single-Leg Romanian Deadlift",
    aliases: ["SL RDL"],
    pattern: "hinge",
    category: "accessory",
    equipment: ["dumbbell", "kettlebell"],
    primary: ["hamstrings", "glutes"],
    secondary: ["erectors", "abs"],
    laterality: "unilateral",
    vector: "vertical",
    metrics: RESIST,
    difficulty: 3,
    progressionOf: "romanian-deadlift",
    tags: ["unilateral", "balance"],
  },
  {
    name: "Stiff-Leg Deadlift",
    pattern: "hinge",
    category: "accessory",
    equipment: ["barbell"],
    primary: ["hamstrings", "glutes"],
    secondary: ["erectors"],
    vector: "vertical",
    metrics: RESIST,
    difficulty: 3,
    tags: ["posterior_chain"],
  },
  {
    name: "Good Morning",
    pattern: "hinge",
    category: "accessory",
    equipment: ["barbell"],
    primary: ["hamstrings", "erectors"],
    secondary: ["glutes"],
    vector: "vertical",
    metrics: RESIST,
    difficulty: 4,
    rest: 120,
    tags: ["posterior_chain", "conjugate"],
  },
  {
    name: "Barbell Hip Thrust",
    pattern: "hinge",
    category: "accessory",
    equipment: ["barbell", "bench"],
    primary: ["glutes"],
    secondary: ["hamstrings"],
    vector: "horizontal",
    metrics: RESIST,
    difficulty: 2,
    cues: ["Ribs down", "Chin tucked", "Squeeze at lockout"],
    rest: 120,
    tags: ["glute_dominant"],
  },
  {
    name: "Glute Bridge",
    pattern: "hinge",
    category: "warmup",
    equipment: ["bodyweight"],
    primary: ["glutes"],
    secondary: ["hamstrings"],
    vector: "horizontal",
    metrics: BW,
    loadBasis: "bodyweight",
    difficulty: 1,
    tags: ["activation"],
  },
  {
    name: "Back Extension",
    pattern: "hinge",
    category: "accessory",
    equipment: ["ghd", "plate"],
    primary: ["erectors", "glutes"],
    secondary: ["hamstrings"],
    vector: "vertical",
    metrics: RESIST,
    difficulty: 2,
    tags: ["posterior_chain"],
  },
  {
    name: "45-Degree Hyperextension",
    pattern: "hinge",
    category: "accessory",
    equipment: ["ghd", "plate"],
    primary: ["erectors", "glutes"],
    vector: "vertical",
    metrics: RESIST,
    difficulty: 2,
    tags: ["posterior_chain"],
  },
  {
    name: "Reverse Hyper",
    pattern: "hinge",
    category: "accessory",
    equipment: ["reverse_hyper"],
    primary: ["glutes", "hamstrings", "erectors"],
    vector: "horizontal",
    metrics: RESIST,
    difficulty: 2,
    tags: ["conjugate", "restoration"],
  },
  {
    name: "Nordic Hamstring Curl",
    pattern: "hinge",
    category: "accessory",
    equipment: ["bodyweight"],
    primary: ["hamstrings"],
    vector: "horizontal",
    contraction: "eccentric",
    metrics: BW,
    loadBasis: "bodyweight",
    difficulty: 5,
    cues: ["Resist all the way down", "Hips locked out"],
    tempo: "5-0-1-0",
    tags: ["injury_prevention", "eccentric", "hamstring"],
  },
  {
    name: "Kettlebell Swing",
    pattern: "hinge",
    category: "conditioning",
    equipment: ["kettlebell"],
    primary: ["glutes", "hamstrings"],
    secondary: ["erectors", "abs"],
    vector: "horizontal",
    contraction: "ballistic",
    metrics: ["reps", "load", "time", "rpe"],
    difficulty: 2,
    cues: ["Hips snap, arms are ropes", "Float at the top"],
    tags: ["power_endurance", "ballistic"],
  },
  {
    name: "Rack Pull",
    pattern: "hinge",
    category: "accessory",
    equipment: ["barbell", "rack"],
    primary: ["erectors", "traps", "glutes"],
    vector: "vertical",
    metrics: STRENGTH,
    loadBasis: "derived_from_exercise",
    derivedFrom: "deadlift",
    derivedRatio: 1.1,
    difficulty: 3,
    tags: ["overload", "lockout"],
  },
  {
    name: "Deficit Deadlift",
    pattern: "hinge",
    category: "accessory",
    equipment: ["barbell", "plate"],
    primary: ["glutes", "hamstrings", "quads"],
    secondary: ["erectors"],
    vector: "vertical",
    metrics: STRENGTH,
    loadBasis: "derived_from_exercise",
    derivedFrom: "deadlift",
    derivedRatio: 0.85,
    difficulty: 4,
    tags: ["off_the_floor"],
  },
  {
    name: "Cable Pull-Through",
    pattern: "hinge",
    category: "accessory",
    equipment: ["cable"],
    primary: ["glutes", "hamstrings"],
    vector: "horizontal",
    metrics: RESIST,
    difficulty: 1,
    tags: ["hinge_pattern_teaching"],
  },
  {
    name: "GHD Raise",
    aliases: ["Glute Ham Raise"],
    pattern: "hinge",
    category: "accessory",
    equipment: ["ghd"],
    primary: ["hamstrings"],
    secondary: ["glutes", "calves"],
    vector: "horizontal",
    metrics: BW,
    loadBasis: "bodyweight",
    difficulty: 4,
    tags: ["hamstring", "injury_prevention"],
  },

  /* ============================== LUNGE ============================== */
  {
    name: "Walking Lunge",
    pattern: "lunge",
    category: "accessory",
    equipment: ["dumbbell", "barbell"],
    primary: ["quads", "glutes"],
    secondary: ["adductors", "hamstrings"],
    laterality: "alternating",
    vector: "vertical",
    metrics: ["load", "reps", "distance", "rpe"],
    difficulty: 2,
    rest: 90,
    tags: ["unilateral"],
  },
  {
    name: "Reverse Lunge",
    pattern: "lunge",
    category: "accessory",
    equipment: ["dumbbell", "barbell"],
    primary: ["glutes", "quads"],
    laterality: "alternating",
    vector: "vertical",
    metrics: RESIST,
    difficulty: 2,
    cues: ["Step back and down", "Torso stays tall"],
    tags: ["unilateral", "knee_friendly"],
  },
  {
    name: "Forward Lunge",
    pattern: "lunge",
    category: "accessory",
    equipment: ["dumbbell"],
    primary: ["quads", "glutes"],
    laterality: "alternating",
    vector: "vertical",
    metrics: RESIST,
    difficulty: 2,
    tags: ["unilateral", "deceleration"],
  },
  {
    name: "Lateral Lunge",
    pattern: "lunge",
    category: "accessory",
    equipment: ["dumbbell", "bodyweight"],
    primary: ["adductors", "glutes", "quads"],
    laterality: "alternating",
    vector: "lateral",
    metrics: RESIST,
    difficulty: 2,
    tags: ["frontal_plane", "groin_health"],
  },
  {
    name: "Curtsy Lunge",
    pattern: "lunge",
    category: "accessory",
    equipment: ["dumbbell", "bodyweight"],
    primary: ["glutes", "abductors"],
    laterality: "alternating",
    vector: "rotational",
    metrics: RESIST,
    difficulty: 2,
    tags: ["frontal_plane"],
  },
  {
    name: "Step-Up",
    pattern: "lunge",
    category: "accessory",
    equipment: ["dumbbell", "box"],
    primary: ["quads", "glutes"],
    laterality: "unilateral",
    vector: "vertical",
    metrics: RESIST,
    difficulty: 2,
    cues: ["Drive through the whole foot", "No push-off from the trail leg"],
    tags: ["unilateral"],
  },
  {
    name: "Lateral Step-Up",
    pattern: "lunge",
    category: "accessory",
    equipment: ["dumbbell", "box"],
    primary: ["glutes", "quads"],
    laterality: "unilateral",
    vector: "lateral",
    metrics: RESIST,
    difficulty: 2,
    tags: ["frontal_plane"],
  },
  {
    name: "Deficit Reverse Lunge",
    pattern: "lunge",
    category: "accessory",
    equipment: ["dumbbell", "box"],
    primary: ["glutes", "quads"],
    laterality: "alternating",
    vector: "vertical",
    metrics: RESIST,
    difficulty: 3,
    progressionOf: "reverse-lunge",
    tags: ["unilateral", "range_of_motion"],
  },
  {
    name: "Skater Squat",
    pattern: "lunge",
    category: "accessory",
    equipment: ["bodyweight", "dumbbell"],
    primary: ["quads", "glutes"],
    laterality: "unilateral",
    vector: "vertical",
    metrics: RESIST,
    difficulty: 4,
    progressionOf: "bulgarian-split-squat",
    tags: ["unilateral", "advanced"],
  },

  /* ========================== VERTICAL PUSH ========================== */
  {
    name: "Overhead Press",
    aliases: ["Military Press", "Strict Press", "OHP"],
    pattern: "vertical_push",
    category: "main_lift",
    equipment: ["barbell"],
    primary: ["front_delts"],
    secondary: ["triceps", "abs", "side_delts"],
    vector: "vertical",
    metrics: STRENGTH,
    loadBasis: "own_1rm",
    maxTestable: true,
    difficulty: 3,
    cues: ["Squeeze the glutes", "Head through at lockout"],
    rest: 150,
    tags: ["compound", "upper_body", "test_lift"],
  },
  {
    name: "Push Press",
    pattern: "vertical_push",
    category: "main_lift",
    equipment: ["barbell"],
    primary: ["front_delts", "triceps"],
    secondary: ["quads", "glutes"],
    vector: "vertical",
    contraction: "ballistic",
    metrics: STRENGTH,
    loadBasis: "derived_from_exercise",
    derivedFrom: "overhead-press",
    derivedRatio: 1.25,
    difficulty: 3,
    cues: ["Short dip, violent drive"],
    tags: ["power", "compound"],
  },
  {
    name: "Push Jerk",
    pattern: "vertical_push",
    category: "skill",
    equipment: ["barbell"],
    primary: ["front_delts", "triceps"],
    secondary: ["quads", "glutes"],
    vector: "vertical",
    contraction: "ballistic",
    metrics: STRENGTH,
    difficulty: 4,
    tags: ["weightlifting", "power"],
  },
  {
    name: "Split Jerk",
    pattern: "vertical_push",
    category: "skill",
    equipment: ["barbell"],
    primary: ["front_delts", "triceps"],
    secondary: ["quads", "glutes"],
    vector: "vertical",
    contraction: "ballistic",
    metrics: STRENGTH,
    difficulty: 5,
    progressionOf: "push-jerk",
    tags: ["weightlifting", "power"],
  },
  {
    name: "Seated Dumbbell Shoulder Press",
    pattern: "vertical_push",
    category: "accessory",
    equipment: ["dumbbell", "bench"],
    primary: ["front_delts"],
    secondary: ["triceps", "side_delts"],
    vector: "vertical",
    metrics: RESIST,
    difficulty: 2,
    rest: 90,
    tags: ["hypertrophy"],
  },
  {
    name: "Standing Dumbbell Press",
    pattern: "vertical_push",
    category: "accessory",
    equipment: ["dumbbell"],
    primary: ["front_delts"],
    secondary: ["triceps", "abs"],
    vector: "vertical",
    metrics: RESIST,
    difficulty: 2,
    tags: ["hypertrophy"],
  },
  {
    name: "Arnold Press",
    pattern: "vertical_push",
    category: "accessory",
    equipment: ["dumbbell"],
    primary: ["front_delts", "side_delts"],
    secondary: ["triceps"],
    vector: "vertical",
    metrics: RESIST,
    difficulty: 2,
    tags: ["hypertrophy"],
  },
  {
    name: "Landmine Press",
    pattern: "vertical_push",
    category: "accessory",
    equipment: ["landmine", "barbell"],
    primary: ["front_delts"],
    secondary: ["triceps", "serratus"],
    laterality: "unilateral",
    vector: "vertical",
    metrics: RESIST,
    difficulty: 2,
    tags: ["shoulder_friendly"],
  },
  {
    name: "Z-Press",
    pattern: "vertical_push",
    category: "accessory",
    equipment: ["barbell", "dumbbell"],
    primary: ["front_delts"],
    secondary: ["abs", "triceps"],
    vector: "vertical",
    metrics: RESIST,
    difficulty: 4,
    tags: ["core_demand"],
  },
  {
    name: "Machine Shoulder Press",
    pattern: "vertical_push",
    category: "accessory",
    equipment: ["machine"],
    primary: ["front_delts"],
    secondary: ["triceps"],
    vector: "vertical",
    metrics: RESIST,
    difficulty: 1,
    tags: ["hypertrophy", "rehab_friendly"],
  },
  {
    name: "Pike Push-Up",
    pattern: "vertical_push",
    category: "accessory",
    equipment: ["bodyweight"],
    primary: ["front_delts"],
    secondary: ["triceps"],
    vector: "vertical",
    metrics: BW,
    loadBasis: "bodyweight",
    difficulty: 3,
    tags: ["calisthenics"],
  },
  {
    name: "Handstand Push-Up",
    pattern: "vertical_push",
    category: "skill",
    equipment: ["bodyweight"],
    primary: ["front_delts", "triceps"],
    vector: "vertical",
    metrics: BW,
    loadBasis: "bodyweight",
    difficulty: 5,
    progressionOf: "pike-push-up",
    tags: ["calisthenics", "advanced"],
  },

  /* ========================= HORIZONTAL PUSH ========================= */
  {
    name: "Bench Press",
    aliases: ["Barbell Bench Press", "Flat Bench"],
    pattern: "horizontal_push",
    category: "main_lift",
    equipment: ["barbell", "bench"],
    primary: ["pecs"],
    secondary: ["triceps", "front_delts"],
    vector: "horizontal",
    metrics: STRENGTH,
    loadBasis: "own_1rm",
    maxTestable: true,
    difficulty: 3,
    cues: ["Shoulder blades pinned", "Bar to the sternum", "Leg drive"],
    rest: 180,
    tags: ["compound", "upper_body", "test_lift"],
  },
  {
    name: "Incline Bench Press",
    pattern: "horizontal_push",
    category: "main_lift",
    equipment: ["barbell", "bench"],
    primary: ["pecs", "front_delts"],
    secondary: ["triceps"],
    vector: "horizontal",
    metrics: STRENGTH,
    loadBasis: "derived_from_exercise",
    derivedFrom: "bench-press",
    derivedRatio: 0.85,
    difficulty: 3,
    rest: 150,
    tags: ["compound", "upper_chest"],
  },
  {
    name: "Close-Grip Bench Press",
    pattern: "horizontal_push",
    category: "accessory",
    equipment: ["barbell", "bench"],
    primary: ["triceps", "pecs"],
    vector: "horizontal",
    metrics: STRENGTH,
    loadBasis: "derived_from_exercise",
    derivedFrom: "bench-press",
    derivedRatio: 0.85,
    difficulty: 3,
    tags: ["triceps", "lockout"],
  },
  {
    name: "Decline Bench Press",
    pattern: "horizontal_push",
    category: "accessory",
    equipment: ["barbell", "bench"],
    primary: ["pecs"],
    secondary: ["triceps"],
    vector: "horizontal",
    metrics: RESIST,
    difficulty: 3,
    tags: ["hypertrophy"],
  },
  {
    name: "Dumbbell Bench Press",
    pattern: "horizontal_push",
    category: "accessory",
    equipment: ["dumbbell", "bench"],
    primary: ["pecs"],
    secondary: ["triceps", "front_delts"],
    vector: "horizontal",
    metrics: RESIST,
    difficulty: 2,
    rest: 120,
    tags: ["hypertrophy"],
  },
  {
    name: "Incline Dumbbell Press",
    pattern: "horizontal_push",
    category: "accessory",
    equipment: ["dumbbell", "bench"],
    primary: ["pecs", "front_delts"],
    secondary: ["triceps"],
    vector: "horizontal",
    metrics: RESIST,
    difficulty: 2,
    tags: ["hypertrophy", "upper_chest"],
  },
  {
    name: "Floor Press",
    pattern: "horizontal_push",
    category: "accessory",
    equipment: ["barbell", "dumbbell"],
    primary: ["pecs", "triceps"],
    vector: "horizontal",
    metrics: RESIST,
    difficulty: 3,
    tags: ["conjugate", "lockout", "shoulder_friendly"],
  },
  {
    name: "Push-Up",
    pattern: "horizontal_push",
    category: "accessory",
    equipment: ["bodyweight"],
    primary: ["pecs"],
    secondary: ["triceps", "front_delts", "abs"],
    vector: "horizontal",
    metrics: BW,
    loadBasis: "bodyweight",
    difficulty: 2,
    cues: ["Body in one line", "Elbows at 45 degrees"],
    tags: ["calisthenics", "beginner_friendly"],
  },
  {
    name: "Weighted Push-Up",
    pattern: "horizontal_push",
    category: "accessory",
    equipment: ["bodyweight", "plate"],
    primary: ["pecs"],
    secondary: ["triceps"],
    vector: "horizontal",
    metrics: BW,
    difficulty: 3,
    progressionOf: "push-up",
    tags: ["calisthenics"],
  },
  {
    name: "Machine Chest Press",
    pattern: "horizontal_push",
    category: "accessory",
    equipment: ["machine"],
    primary: ["pecs"],
    secondary: ["triceps"],
    vector: "horizontal",
    metrics: RESIST,
    difficulty: 1,
    tags: ["hypertrophy", "rehab_friendly"],
  },
  {
    name: "Cable Fly",
    pattern: "horizontal_push",
    category: "accessory",
    equipment: ["cable"],
    primary: ["pecs"],
    vector: "horizontal",
    metrics: RESIST,
    difficulty: 2,
    tags: ["isolation", "hypertrophy"],
  },
  {
    name: "Dumbbell Fly",
    pattern: "horizontal_push",
    category: "accessory",
    equipment: ["dumbbell", "bench"],
    primary: ["pecs"],
    vector: "horizontal",
    metrics: RESIST,
    difficulty: 2,
    tags: ["isolation", "hypertrophy"],
  },
  {
    name: "Dip",
    pattern: "horizontal_push",
    category: "accessory",
    equipment: ["dip_station"],
    primary: ["pecs", "triceps"],
    secondary: ["front_delts"],
    vector: "vertical",
    metrics: BW,
    loadBasis: "bodyweight",
    difficulty: 3,
    tags: ["calisthenics"],
  },

  /* ========================== VERTICAL PULL ========================== */
  {
    name: "Pull-Up",
    pattern: "vertical_pull",
    category: "main_lift",
    equipment: ["pull_up_bar"],
    primary: ["lats"],
    secondary: ["biceps", "rhomboids", "forearms"],
    vector: "vertical",
    metrics: BW,
    loadBasis: "bodyweight",
    difficulty: 3,
    cues: ["Chest to the bar", "Drive elbows to the ribs"],
    rest: 120,
    tags: ["calisthenics", "compound"],
  },
  {
    name: "Chin-Up",
    pattern: "vertical_pull",
    category: "accessory",
    equipment: ["pull_up_bar"],
    primary: ["lats", "biceps"],
    vector: "vertical",
    metrics: BW,
    loadBasis: "bodyweight",
    difficulty: 3,
    tags: ["calisthenics"],
  },
  {
    name: "Weighted Pull-Up",
    pattern: "vertical_pull",
    category: "accessory",
    equipment: ["pull_up_bar", "plate"],
    primary: ["lats"],
    secondary: ["biceps"],
    vector: "vertical",
    metrics: BW,
    difficulty: 4,
    progressionOf: "pull-up",
    tags: ["calisthenics", "strength"],
  },
  {
    name: "Assisted Pull-Up",
    pattern: "vertical_pull",
    category: "accessory",
    equipment: ["band", "machine"],
    primary: ["lats"],
    secondary: ["biceps"],
    vector: "vertical",
    metrics: ["reps", "load", "rpe", "band_level"],
    difficulty: 2,
    tags: ["beginner_friendly", "regression"],
  },
  {
    name: "Neutral-Grip Pull-Up",
    pattern: "vertical_pull",
    category: "accessory",
    equipment: ["pull_up_bar"],
    primary: ["lats", "biceps"],
    vector: "vertical",
    metrics: BW,
    loadBasis: "bodyweight",
    difficulty: 3,
    tags: ["shoulder_friendly"],
  },
  {
    name: "Lat Pulldown",
    pattern: "vertical_pull",
    category: "accessory",
    equipment: ["cable", "machine"],
    primary: ["lats"],
    secondary: ["biceps", "rhomboids"],
    vector: "vertical",
    metrics: RESIST,
    difficulty: 1,
    rest: 90,
    tags: ["hypertrophy"],
  },
  {
    name: "Straight-Arm Pulldown",
    pattern: "vertical_pull",
    category: "accessory",
    equipment: ["cable"],
    primary: ["lats"],
    vector: "vertical",
    metrics: RESIST,
    difficulty: 2,
    tags: ["isolation"],
  },
  {
    name: "Scapular Pull-Up",
    pattern: "vertical_pull",
    category: "corrective",
    equipment: ["pull_up_bar"],
    primary: ["lats", "traps"],
    vector: "vertical",
    metrics: BW,
    loadBasis: "bodyweight",
    difficulty: 1,
    tags: ["activation", "scapular_control"],
  },
  {
    name: "Half-Kneeling Single-Arm Pulldown",
    pattern: "vertical_pull",
    category: "accessory",
    equipment: ["cable"],
    primary: ["lats"],
    secondary: ["abs"],
    laterality: "unilateral",
    vector: "vertical",
    metrics: RESIST,
    difficulty: 2,
    tags: ["unilateral", "anti_rotation"],
  },

  /* ========================= HORIZONTAL PULL ========================= */
  {
    name: "Barbell Row",
    aliases: ["Bent-Over Row"],
    pattern: "horizontal_pull",
    category: "main_lift",
    equipment: ["barbell"],
    primary: ["lats", "rhomboids"],
    secondary: ["biceps", "erectors", "rear_delts"],
    vector: "horizontal",
    metrics: STRENGTH,
    loadBasis: "own_1rm",
    maxTestable: true,
    difficulty: 3,
    cues: ["Hinge to 45 degrees", "Bar to the belly button"],
    rest: 120,
    tags: ["compound", "upper_back"],
  },
  {
    name: "Pendlay Row",
    pattern: "horizontal_pull",
    category: "accessory",
    equipment: ["barbell"],
    primary: ["lats", "rhomboids"],
    secondary: ["erectors", "biceps"],
    vector: "horizontal",
    contraction: "concentric",
    metrics: RESIST,
    difficulty: 4,
    tags: ["explosive", "upper_back"],
  },
  {
    name: "Single-Arm Dumbbell Row",
    pattern: "horizontal_pull",
    category: "accessory",
    equipment: ["dumbbell", "bench"],
    primary: ["lats"],
    secondary: ["biceps", "rhomboids"],
    laterality: "unilateral",
    vector: "horizontal",
    metrics: RESIST,
    difficulty: 2,
    rest: 90,
    tags: ["unilateral", "hypertrophy"],
  },
  {
    name: "Chest-Supported Row",
    pattern: "horizontal_pull",
    category: "accessory",
    equipment: ["dumbbell", "bench"],
    primary: ["rhomboids", "lats"],
    secondary: ["rear_delts", "biceps"],
    vector: "horizontal",
    metrics: RESIST,
    difficulty: 1,
    tags: ["spine_sparing", "hypertrophy"],
  },
  {
    name: "T-Bar Row",
    pattern: "horizontal_pull",
    category: "accessory",
    equipment: ["landmine", "barbell"],
    primary: ["lats", "rhomboids"],
    secondary: ["biceps"],
    vector: "horizontal",
    metrics: RESIST,
    difficulty: 2,
    tags: ["hypertrophy", "upper_back"],
  },
  {
    name: "Seated Cable Row",
    pattern: "horizontal_pull",
    category: "accessory",
    equipment: ["cable"],
    primary: ["lats", "rhomboids"],
    secondary: ["biceps"],
    vector: "horizontal",
    metrics: RESIST,
    difficulty: 1,
    rest: 90,
    tags: ["hypertrophy"],
  },
  {
    name: "Inverted Row",
    aliases: ["Ring Row", "Body Row"],
    pattern: "horizontal_pull",
    category: "accessory",
    equipment: ["barbell", "suspension_trainer"],
    primary: ["rhomboids", "lats"],
    secondary: ["biceps", "abs"],
    vector: "horizontal",
    metrics: BW,
    loadBasis: "bodyweight",
    difficulty: 2,
    tags: ["calisthenics", "beginner_friendly"],
  },
  {
    name: "Meadows Row",
    pattern: "horizontal_pull",
    category: "accessory",
    equipment: ["landmine", "barbell"],
    primary: ["lats"],
    secondary: ["rear_delts", "biceps"],
    laterality: "unilateral",
    vector: "horizontal",
    metrics: RESIST,
    difficulty: 3,
    tags: ["hypertrophy"],
  },
  {
    name: "Machine Row",
    pattern: "horizontal_pull",
    category: "accessory",
    equipment: ["machine"],
    primary: ["lats", "rhomboids"],
    vector: "horizontal",
    metrics: RESIST,
    difficulty: 1,
    tags: ["hypertrophy", "rehab_friendly"],
  },
  {
    name: "Face Pull",
    pattern: "horizontal_pull",
    category: "corrective",
    equipment: ["cable", "band"],
    primary: ["rear_delts", "rotator_cuff"],
    secondary: ["traps", "rhomboids"],
    vector: "horizontal",
    metrics: RESIST,
    difficulty: 1,
    cues: ["Pull to the forehead", "External rotation at the end"],
    tags: ["shoulder_health", "postural"],
  },
  {
    name: "Landmine Row",
    pattern: "horizontal_pull",
    category: "accessory",
    equipment: ["landmine", "barbell"],
    primary: ["lats", "rhomboids"],
    vector: "horizontal",
    metrics: RESIST,
    difficulty: 2,
    tags: ["upper_back"],
  },
  {
    name: "Seal Row",
    pattern: "horizontal_pull",
    category: "accessory",
    equipment: ["barbell", "bench"],
    primary: ["lats", "rhomboids"],
    secondary: ["rear_delts"],
    vector: "horizontal",
    metrics: RESIST,
    difficulty: 2,
    tags: ["strict", "hypertrophy"],
  },

  /* ============================ OLYMPIC ============================= */
  {
    name: "Power Clean",
    pattern: "olympic",
    category: "main_lift",
    equipment: ["barbell"],
    primary: ["glutes", "hamstrings", "traps"],
    secondary: ["quads", "front_delts"],
    vector: "vertical",
    contraction: "ballistic",
    metrics: STRENGTH,
    loadBasis: "own_1rm",
    maxTestable: true,
    difficulty: 5,
    cues: ["Patient off the floor", "Violent hip extension", "Fast elbows"],
    rest: 180,
    tags: ["weightlifting", "power", "test_lift"],
  },
  {
    name: "Hang Power Clean",
    pattern: "olympic",
    category: "main_lift",
    equipment: ["barbell"],
    primary: ["glutes", "traps", "hamstrings"],
    vector: "vertical",
    contraction: "ballistic",
    metrics: STRENGTH,
    loadBasis: "derived_from_exercise",
    derivedFrom: "power-clean",
    derivedRatio: 0.9,
    difficulty: 4,
    tags: ["weightlifting", "power"],
  },
  {
    name: "Clean",
    aliases: ["Squat Clean", "Full Clean"],
    pattern: "olympic",
    category: "skill",
    equipment: ["barbell"],
    primary: ["glutes", "quads", "traps"],
    vector: "vertical",
    contraction: "ballistic",
    metrics: STRENGTH,
    maxTestable: true,
    difficulty: 5,
    progressionOf: "power-clean",
    tags: ["weightlifting"],
  },
  {
    name: "Clean and Jerk",
    pattern: "olympic",
    category: "skill",
    equipment: ["barbell"],
    primary: ["glutes", "quads", "front_delts"],
    secondary: ["traps", "triceps"],
    vector: "vertical",
    contraction: "ballistic",
    metrics: STRENGTH,
    maxTestable: true,
    difficulty: 5,
    tags: ["weightlifting", "competition_lift"],
  },
  {
    name: "Clean Pull",
    pattern: "olympic",
    category: "accessory",
    equipment: ["barbell"],
    primary: ["glutes", "hamstrings", "traps"],
    vector: "vertical",
    contraction: "ballistic",
    metrics: STRENGTH,
    loadBasis: "derived_from_exercise",
    derivedFrom: "power-clean",
    derivedRatio: 1.1,
    difficulty: 3,
    tags: ["weightlifting", "overload"],
  },
  {
    name: "Clean High Pull",
    pattern: "olympic",
    category: "accessory",
    equipment: ["barbell"],
    primary: ["traps", "glutes"],
    vector: "vertical",
    contraction: "ballistic",
    metrics: STRENGTH,
    difficulty: 3,
    tags: ["weightlifting"],
  },
  {
    name: "Clean Deadlift",
    pattern: "olympic",
    category: "accessory",
    equipment: ["barbell"],
    primary: ["glutes", "hamstrings", "erectors"],
    vector: "vertical",
    metrics: STRENGTH,
    difficulty: 3,
    tags: ["weightlifting", "positional_strength"],
  },
  {
    name: "Snatch",
    pattern: "olympic",
    category: "skill",
    equipment: ["barbell"],
    primary: ["glutes", "traps", "front_delts"],
    secondary: ["quads", "hamstrings"],
    vector: "vertical",
    contraction: "ballistic",
    metrics: STRENGTH,
    maxTestable: true,
    difficulty: 5,
    tags: ["weightlifting", "competition_lift"],
  },
  {
    name: "Power Snatch",
    pattern: "olympic",
    category: "main_lift",
    equipment: ["barbell"],
    primary: ["glutes", "traps", "front_delts"],
    vector: "vertical",
    contraction: "ballistic",
    metrics: STRENGTH,
    loadBasis: "own_1rm",
    maxTestable: true,
    difficulty: 5,
    tags: ["weightlifting", "power"],
  },
  {
    name: "Hang Power Snatch",
    pattern: "olympic",
    category: "accessory",
    equipment: ["barbell"],
    primary: ["glutes", "traps"],
    vector: "vertical",
    contraction: "ballistic",
    metrics: STRENGTH,
    loadBasis: "derived_from_exercise",
    derivedFrom: "power-snatch",
    derivedRatio: 0.9,
    difficulty: 4,
    tags: ["weightlifting", "power"],
  },
  {
    name: "Snatch Pull",
    pattern: "olympic",
    category: "accessory",
    equipment: ["barbell"],
    primary: ["glutes", "hamstrings", "traps"],
    vector: "vertical",
    contraction: "ballistic",
    metrics: STRENGTH,
    loadBasis: "derived_from_exercise",
    derivedFrom: "power-snatch",
    derivedRatio: 1.1,
    difficulty: 3,
    tags: ["weightlifting", "overload"],
  },
  {
    name: "Muscle Snatch",
    pattern: "olympic",
    category: "accessory",
    equipment: ["barbell"],
    primary: ["traps", "front_delts"],
    vector: "vertical",
    contraction: "ballistic",
    metrics: STRENGTH,
    difficulty: 4,
    tags: ["weightlifting", "technique"],
  },

  /* ============================== CARRY ============================== */
  {
    name: "Farmer's Carry",
    pattern: "carry",
    category: "accessory",
    equipment: ["dumbbell", "kettlebell", "trap_bar"],
    primary: ["forearms", "traps"],
    secondary: ["abs", "glutes"],
    vector: "vertical",
    contraction: "isometric",
    metrics: ["load", "distance", "time", "rpe"],
    difficulty: 2,
    cues: ["Tall posture", "Ribs stacked over the pelvis"],
    tags: ["grip", "core", "gpp"],
  },
  {
    name: "Suitcase Carry",
    pattern: "carry",
    category: "accessory",
    equipment: ["dumbbell", "kettlebell"],
    primary: ["obliques", "forearms"],
    secondary: ["abs"],
    laterality: "unilateral",
    vector: "vertical",
    contraction: "isometric",
    metrics: ["load", "distance", "time", "rpe"],
    difficulty: 2,
    tags: ["anti_lateral_flexion", "core"],
  },
  {
    name: "Front Rack Carry",
    pattern: "carry",
    category: "accessory",
    equipment: ["kettlebell", "dumbbell"],
    primary: ["abs", "traps"],
    secondary: ["front_delts"],
    vector: "vertical",
    contraction: "isometric",
    metrics: ["load", "distance", "time", "rpe"],
    difficulty: 3,
    tags: ["core", "postural"],
  },
  {
    name: "Overhead Carry",
    pattern: "carry",
    category: "accessory",
    equipment: ["kettlebell", "dumbbell"],
    primary: ["front_delts", "abs"],
    secondary: ["traps", "rotator_cuff"],
    vector: "vertical",
    contraction: "isometric",
    metrics: ["load", "distance", "time", "rpe"],
    difficulty: 3,
    tags: ["shoulder_stability", "core"],
  },
  {
    name: "Yoke Walk",
    pattern: "carry",
    category: "accessory",
    equipment: ["specialty_bar"],
    primary: ["erectors", "traps", "quads"],
    secondary: ["abs"],
    vector: "vertical",
    contraction: "isometric",
    metrics: ["load", "distance", "time", "rpe"],
    difficulty: 4,
    tags: ["strongman"],
  },
  {
    name: "Sandbag Carry",
    pattern: "carry",
    category: "conditioning",
    equipment: ["specialty_bar"],
    primary: ["abs", "erectors"],
    secondary: ["glutes", "traps"],
    vector: "vertical",
    metrics: ["load", "distance", "time", "rpe"],
    difficulty: 3,
    tags: ["strongman", "gpp"],
  },

  /* ======================= CORE / ANTI-MOVEMENT ====================== */
  {
    name: "Plank",
    pattern: "anti_extension",
    category: "accessory",
    equipment: ["bodyweight"],
    primary: ["abs"],
    secondary: ["obliques", "front_delts"],
    contraction: "isometric",
    metrics: TIMED,
    loadBasis: "bodyweight",
    difficulty: 1,
    cues: ["Ribs down, glutes on", "Push the floor away"],
    tags: ["core", "isometric"],
  },
  {
    name: "RKC Plank",
    pattern: "anti_extension",
    category: "accessory",
    equipment: ["bodyweight"],
    primary: ["abs"],
    contraction: "isometric",
    metrics: TIMED,
    loadBasis: "bodyweight",
    difficulty: 3,
    progressionOf: "plank",
    tags: ["core", "isometric"],
  },
  {
    name: "Side Plank",
    pattern: "anti_lateral_flexion",
    category: "accessory",
    equipment: ["bodyweight"],
    primary: ["obliques"],
    secondary: ["abs", "abductors"],
    laterality: "unilateral",
    contraction: "isometric",
    metrics: TIMED,
    loadBasis: "bodyweight",
    difficulty: 2,
    tags: ["core", "isometric"],
  },
  {
    name: "Copenhagen Plank",
    pattern: "anti_lateral_flexion",
    category: "corrective",
    equipment: ["bench", "bodyweight"],
    primary: ["adductors"],
    secondary: ["obliques"],
    laterality: "unilateral",
    contraction: "isometric",
    metrics: TIMED,
    loadBasis: "bodyweight",
    difficulty: 4,
    tags: ["groin_health", "injury_prevention"],
  },
  {
    name: "Pallof Press",
    pattern: "anti_rotation",
    category: "accessory",
    equipment: ["cable", "band"],
    primary: ["obliques", "abs"],
    laterality: "unilateral",
    vector: "rotational",
    contraction: "isometric",
    metrics: ["load", "reps", "time", "rpe"],
    difficulty: 2,
    cues: ["Resist the rotation", "Breathe out at full extension"],
    tags: ["core", "anti_rotation"],
  },
  {
    name: "Half-Kneeling Pallof Press",
    pattern: "anti_rotation",
    category: "accessory",
    equipment: ["cable", "band"],
    primary: ["obliques", "abs"],
    secondary: ["glutes"],
    laterality: "unilateral",
    vector: "rotational",
    metrics: ["load", "reps", "time", "rpe"],
    difficulty: 3,
    progressionOf: "pallof-press",
    tags: ["core", "anti_rotation"],
  },
  {
    name: "Ab Wheel Rollout",
    pattern: "anti_extension",
    category: "accessory",
    equipment: ["bodyweight"],
    primary: ["abs"],
    secondary: ["lats", "obliques"],
    contraction: "eccentric",
    metrics: BW,
    loadBasis: "bodyweight",
    difficulty: 4,
    progressionOf: "plank",
    tags: ["core", "advanced"],
  },
  {
    name: "Dead Bug",
    pattern: "anti_extension",
    category: "corrective",
    equipment: ["bodyweight"],
    primary: ["abs"],
    laterality: "alternating",
    metrics: MOBI,
    loadBasis: "bodyweight",
    difficulty: 1,
    tags: ["core", "beginner_friendly", "rehab_friendly"],
  },
  {
    name: "Bird Dog",
    pattern: "anti_rotation",
    category: "corrective",
    equipment: ["bodyweight"],
    primary: ["erectors", "abs"],
    secondary: ["glutes"],
    laterality: "alternating",
    metrics: MOBI,
    loadBasis: "bodyweight",
    difficulty: 1,
    tags: ["core", "rehab_friendly"],
  },
  {
    name: "Hollow Hold",
    pattern: "anti_extension",
    category: "accessory",
    equipment: ["bodyweight"],
    primary: ["abs"],
    contraction: "isometric",
    metrics: TIMED,
    loadBasis: "bodyweight",
    difficulty: 3,
    tags: ["core", "gymnastics"],
  },
  {
    name: "Hanging Leg Raise",
    pattern: "anti_extension",
    category: "accessory",
    equipment: ["pull_up_bar"],
    primary: ["abs", "hip_flexors"],
    metrics: BW,
    loadBasis: "bodyweight",
    difficulty: 3,
    tags: ["core"],
  },
  {
    name: "Cable Crunch",
    pattern: "anti_extension",
    category: "accessory",
    equipment: ["cable"],
    primary: ["abs"],
    metrics: RESIST,
    difficulty: 2,
    tags: ["core", "hypertrophy"],
  },
  {
    name: "Cable Woodchop",
    pattern: "rotation",
    category: "accessory",
    equipment: ["cable"],
    primary: ["obliques"],
    secondary: ["abs", "front_delts"],
    laterality: "unilateral",
    vector: "rotational",
    metrics: RESIST,
    difficulty: 2,
    tags: ["core", "rotational_power"],
  },
  {
    name: "Landmine Rotation",
    pattern: "rotation",
    category: "accessory",
    equipment: ["landmine", "barbell"],
    primary: ["obliques"],
    secondary: ["abs", "front_delts"],
    vector: "rotational",
    metrics: RESIST,
    difficulty: 3,
    tags: ["core", "rotational_power"],
  },
  {
    name: "Russian Twist",
    pattern: "rotation",
    category: "accessory",
    equipment: ["med_ball", "plate"],
    primary: ["obliques"],
    laterality: "alternating",
    vector: "rotational",
    metrics: RESIST,
    difficulty: 2,
    tags: ["core"],
  },
  {
    name: "Stir the Pot",
    pattern: "anti_extension",
    category: "corrective",
    equipment: ["swiss_ball"],
    primary: ["abs"],
    secondary: ["obliques"],
    contraction: "isometric",
    metrics: MOBI,
    loadBasis: "bodyweight",
    difficulty: 3,
    tags: ["core"],
  },

  /* ========================= JUMP / PLYOMETRIC ======================= */
  {
    name: "Countermovement Jump",
    aliases: ["CMJ", "Vertical Jump"],
    pattern: "jump_land",
    category: "plyometric",
    equipment: ["bodyweight"],
    primary: ["quads", "glutes", "calves"],
    vector: "vertical",
    contraction: "ballistic",
    metrics: JUMP_H,
    loadBasis: "bodyweight",
    difficulty: 2,
    cues: ["Fast down, faster up", "Reach tall"],
    rest: 90,
    tags: ["power", "testing", "monitoring"],
  },
  {
    name: "Squat Jump",
    pattern: "jump_land",
    category: "plyometric",
    equipment: ["bodyweight"],
    primary: ["quads", "glutes"],
    vector: "vertical",
    contraction: "ballistic",
    metrics: JUMP_H,
    loadBasis: "bodyweight",
    difficulty: 2,
    tags: ["power", "concentric_only"],
  },
  {
    name: "Broad Jump",
    aliases: ["Standing Long Jump"],
    pattern: "jump_land",
    category: "plyometric",
    equipment: ["bodyweight"],
    primary: ["glutes", "quads", "hamstrings"],
    vector: "horizontal",
    contraction: "ballistic",
    metrics: JUMP_D,
    loadBasis: "bodyweight",
    difficulty: 2,
    rest: 90,
    tags: ["power", "testing", "horizontal_power"],
  },
  {
    name: "Box Jump",
    pattern: "jump_land",
    category: "plyometric",
    equipment: ["box"],
    primary: ["quads", "glutes"],
    vector: "vertical",
    contraction: "ballistic",
    metrics: ["reps", "height", "rpe"],
    difficulty: 2,
    cues: ["Land soft, land quiet", "Step down, never jump down"],
    tags: ["power"],
  },
  {
    name: "Depth Jump",
    pattern: "jump_land",
    category: "plyometric",
    equipment: ["box"],
    primary: ["quads", "glutes", "calves"],
    vector: "vertical",
    contraction: "ballistic",
    metrics: ["reps", "height", "rpe"],
    difficulty: 5,
    progressionOf: "box-jump",
    cues: ["Minimise ground contact time"],
    tags: ["power", "reactive_strength", "advanced"],
  },
  {
    name: "Drop Landing",
    pattern: "jump_land",
    category: "plyometric",
    equipment: ["box"],
    primary: ["quads", "glutes"],
    vector: "vertical",
    contraction: "eccentric",
    metrics: ["reps", "height", "rpe"],
    difficulty: 2,
    tags: ["landing_mechanics", "injury_prevention"],
  },
  {
    name: "Hurdle Hop",
    pattern: "jump_land",
    category: "plyometric",
    equipment: ["hurdle"],
    primary: ["calves", "quads"],
    vector: "vertical",
    contraction: "ballistic",
    metrics: ["reps", "height", "rpe"],
    difficulty: 3,
    tags: ["reactive_strength"],
  },
  {
    name: "Single-Leg Bound",
    pattern: "jump_land",
    category: "plyometric",
    equipment: ["bodyweight"],
    primary: ["glutes", "hamstrings", "calves"],
    laterality: "unilateral",
    vector: "horizontal",
    contraction: "ballistic",
    metrics: JUMP_D,
    difficulty: 4,
    tags: ["power", "unilateral", "horizontal_power"],
  },
  {
    name: "Lateral Bound",
    pattern: "jump_land",
    category: "plyometric",
    equipment: ["bodyweight"],
    primary: ["glutes", "abductors", "quads"],
    laterality: "alternating",
    vector: "lateral",
    contraction: "ballistic",
    metrics: JUMP_D,
    difficulty: 3,
    tags: ["frontal_plane", "change_of_direction"],
  },
  {
    name: "Pogo Hop",
    pattern: "jump_land",
    category: "plyometric",
    equipment: ["bodyweight"],
    primary: ["calves", "tibialis"],
    vector: "vertical",
    contraction: "ballistic",
    metrics: ["reps", "time", "rpe"],
    difficulty: 1,
    tags: ["stiffness", "warmup"],
  },
  {
    name: "Tuck Jump",
    pattern: "jump_land",
    category: "plyometric",
    equipment: ["bodyweight"],
    primary: ["quads", "hip_flexors"],
    vector: "vertical",
    contraction: "ballistic",
    metrics: ["reps", "rpe"],
    difficulty: 3,
    tags: ["power"],
  },
  {
    name: "Split Jump",
    pattern: "jump_land",
    category: "plyometric",
    equipment: ["bodyweight"],
    primary: ["quads", "glutes"],
    laterality: "alternating",
    vector: "vertical",
    contraction: "ballistic",
    metrics: ["reps", "rpe"],
    difficulty: 3,
    tags: ["power", "unilateral"],
  },
  {
    name: "Trap Bar Jump",
    pattern: "jump_land",
    category: "plyometric",
    equipment: ["trap_bar"],
    primary: ["glutes", "quads"],
    vector: "vertical",
    contraction: "ballistic",
    metrics: ["load", "reps", "height", "velocity", "rpe"],
    difficulty: 3,
    tags: ["loaded_power", "vbt"],
  },

  /* ============================== THROW ============================= */
  {
    name: "Med Ball Chest Pass",
    pattern: "throw",
    category: "plyometric",
    equipment: ["med_ball"],
    primary: ["pecs", "triceps"],
    secondary: ["abs"],
    vector: "horizontal",
    contraction: "ballistic",
    metrics: THROWN,
    difficulty: 1,
    tags: ["upper_body_power"],
  },
  {
    name: "Med Ball Overhead Throw",
    pattern: "throw",
    category: "plyometric",
    equipment: ["med_ball"],
    primary: ["lats", "abs"],
    secondary: ["front_delts"],
    vector: "vertical",
    contraction: "ballistic",
    metrics: THROWN,
    difficulty: 2,
    tags: ["total_body_power"],
  },
  {
    name: "Med Ball Slam",
    pattern: "throw",
    category: "conditioning",
    equipment: ["slam_ball"],
    primary: ["abs", "lats"],
    vector: "vertical",
    contraction: "ballistic",
    metrics: ["reps", "load", "time", "rpe"],
    difficulty: 1,
    tags: ["conditioning", "power_endurance"],
  },
  {
    name: "Med Ball Rotational Throw",
    pattern: "throw",
    category: "plyometric",
    equipment: ["med_ball"],
    primary: ["obliques"],
    secondary: ["glutes", "pecs"],
    laterality: "unilateral",
    vector: "rotational",
    contraction: "ballistic",
    metrics: THROWN,
    difficulty: 2,
    cues: ["Rotate from the hips, not the arms"],
    tags: ["rotational_power", "sport_specific"],
  },
  {
    name: "Med Ball Scoop Toss",
    pattern: "throw",
    category: "plyometric",
    equipment: ["med_ball"],
    primary: ["glutes", "hamstrings"],
    secondary: ["abs"],
    vector: "vertical",
    contraction: "ballistic",
    metrics: THROWN,
    difficulty: 2,
    tags: ["triple_extension", "power"],
  },
  {
    name: "Kneeling Overhead Throw",
    pattern: "throw",
    category: "plyometric",
    equipment: ["med_ball"],
    primary: ["abs", "lats"],
    vector: "vertical",
    contraction: "ballistic",
    metrics: THROWN,
    difficulty: 2,
    tags: ["upper_body_power", "testing"],
  },

  /* ========================== SPRINT / GAIT ========================= */
  {
    name: "Max Velocity Sprint",
    pattern: "sprint",
    category: "conditioning",
    equipment: ["none"],
    primary: ["hamstrings", "glutes", "calves"],
    secondary: ["hip_flexors", "quads"],
    vector: "horizontal",
    contraction: "ballistic",
    metrics: ["distance", "time", "velocity", "rpe"],
    difficulty: 4,
    cues: ["Tall posture", "Punch the ground, don't reach"],
    rest: 300,
    tags: ["speed", "testing", "high_neural"],
  },
  {
    name: "Acceleration Sprint",
    pattern: "sprint",
    category: "conditioning",
    equipment: ["none"],
    primary: ["glutes", "quads"],
    secondary: ["calves"],
    vector: "horizontal",
    contraction: "ballistic",
    metrics: ["distance", "time", "rpe"],
    difficulty: 3,
    cues: ["Push, don't pull", "Gradual rise in the shin angle"],
    rest: 180,
    tags: ["speed", "acceleration"],
  },
  {
    name: "Flying 30m",
    pattern: "sprint",
    category: "conditioning",
    equipment: ["none"],
    primary: ["hamstrings", "glutes"],
    vector: "horizontal",
    contraction: "ballistic",
    metrics: ["distance", "time", "velocity", "rpe"],
    difficulty: 5,
    tags: ["speed", "testing", "max_velocity"],
  },
  {
    name: "Resisted Sled Sprint",
    pattern: "sprint",
    category: "conditioning",
    equipment: ["sled"],
    primary: ["glutes", "quads"],
    vector: "horizontal",
    metrics: SLED,
    difficulty: 3,
    tags: ["acceleration", "speed_strength"],
  },
  {
    name: "Sled Push",
    pattern: "gait",
    category: "conditioning",
    equipment: ["sled"],
    primary: ["quads", "glutes", "calves"],
    vector: "horizontal",
    metrics: SLED,
    difficulty: 2,
    cues: ["Low body angle", "Full leg extension each step"],
    tags: ["conditioning", "acceleration"],
  },
  {
    name: "Sled Drag",
    pattern: "gait",
    category: "conditioning",
    equipment: ["sled"],
    primary: ["glutes", "hamstrings"],
    vector: "horizontal",
    metrics: SLED,
    difficulty: 2,
    tags: ["conditioning", "restoration"],
  },
  {
    name: "Backward Sled Drag",
    pattern: "gait",
    category: "conditioning",
    equipment: ["sled"],
    primary: ["quads"],
    secondary: ["calves"],
    vector: "horizontal",
    metrics: SLED,
    difficulty: 2,
    tags: ["knee_health", "restoration"],
  },
  {
    name: "Hill Sprint",
    pattern: "sprint",
    category: "conditioning",
    equipment: ["none"],
    primary: ["glutes", "quads", "calves"],
    vector: "horizontal",
    metrics: ["distance", "time", "rpe", "heart_rate"],
    difficulty: 3,
    tags: ["acceleration", "conditioning"],
  },
  {
    name: "Tempo Run",
    pattern: "gait",
    category: "conditioning",
    equipment: ["none"],
    primary: ["hamstrings", "quads"],
    vector: "horizontal",
    metrics: RUN,
    difficulty: 2,
    tags: ["aerobic", "recovery"],
  },
  {
    name: "5-10-5 Shuttle",
    aliases: ["Pro Agility"],
    pattern: "sprint",
    category: "conditioning",
    equipment: ["cone"],
    primary: ["quads", "glutes", "adductors"],
    vector: "lateral",
    metrics: ["reps", "time", "rpe"],
    difficulty: 3,
    tags: ["change_of_direction", "testing", "agility"],
  },
  {
    name: "A-Skip",
    pattern: "gait",
    category: "warmup",
    equipment: ["none"],
    primary: ["hip_flexors", "calves"],
    vector: "horizontal",
    metrics: ["distance", "reps"],
    difficulty: 1,
    tags: ["sprint_drill", "warmup"],
  },
  {
    name: "B-Skip",
    pattern: "gait",
    category: "warmup",
    equipment: ["none"],
    primary: ["hamstrings", "hip_flexors"],
    vector: "horizontal",
    metrics: ["distance", "reps"],
    difficulty: 2,
    progressionOf: "a-skip",
    tags: ["sprint_drill", "warmup"],
  },
  {
    name: "Wicket Run",
    pattern: "sprint",
    category: "skill",
    equipment: ["hurdle"],
    primary: ["hamstrings", "glutes"],
    vector: "horizontal",
    metrics: ["distance", "reps", "rpe"],
    difficulty: 4,
    tags: ["max_velocity", "sprint_drill"],
  },

  /* =========================== CONDITIONING ========================= */
  {
    name: "Assault Bike Intervals",
    pattern: "gait",
    category: "conditioning",
    equipment: ["assault_bike"],
    primary: ["quads", "full_body"],
    metrics: CONDI,
    difficulty: 2,
    tags: ["anaerobic", "conditioning"],
  },
  {
    name: "Rowing Intervals",
    pattern: "hinge",
    category: "conditioning",
    equipment: ["rower"],
    primary: ["lats", "quads", "glutes"],
    metrics: CONDI,
    difficulty: 2,
    tags: ["conditioning", "low_impact"],
  },
  {
    name: "Ski Erg Intervals",
    pattern: "vertical_pull",
    category: "conditioning",
    equipment: ["ski_erg"],
    primary: ["lats", "abs", "triceps"],
    metrics: CONDI,
    difficulty: 2,
    tags: ["conditioning", "upper_body"],
  },
  {
    name: "Bike Erg",
    pattern: "gait",
    category: "conditioning",
    equipment: ["bike"],
    primary: ["quads", "glutes"],
    metrics: CONDI,
    difficulty: 1,
    tags: ["aerobic", "low_impact", "recovery"],
  },
  {
    name: "Treadmill Run",
    pattern: "gait",
    category: "conditioning",
    equipment: ["treadmill"],
    primary: ["quads", "hamstrings", "calves"],
    metrics: ["distance", "time", "incline", "heart_rate", "rpe"],
    difficulty: 1,
    tags: ["aerobic"],
  },
  {
    name: "Jump Rope",
    pattern: "jump_land",
    category: "conditioning",
    equipment: ["jump_rope"],
    primary: ["calves"],
    secondary: ["tibialis"],
    metrics: ["time", "reps", "rpe"],
    difficulty: 1,
    tags: ["warmup", "stiffness", "conditioning"],
  },
  {
    name: "Battle Ropes",
    pattern: "isolation",
    category: "conditioning",
    equipment: ["band"],
    primary: ["front_delts", "abs"],
    metrics: ["time", "rpe", "heart_rate"],
    difficulty: 2,
    tags: ["conditioning", "upper_body"],
  },
  {
    name: "Burpee",
    pattern: "jump_land",
    category: "conditioning",
    equipment: ["bodyweight"],
    primary: ["full_body"],
    metrics: ["reps", "time", "rpe"],
    loadBasis: "bodyweight",
    difficulty: 2,
    tags: ["conditioning", "gpp"],
  },
  {
    name: "Wall Ball",
    pattern: "squat",
    category: "conditioning",
    equipment: ["med_ball"],
    primary: ["quads", "glutes", "front_delts"],
    metrics: ["reps", "load", "time", "rpe"],
    difficulty: 2,
    tags: ["conditioning", "crossfit"],
  },
  {
    name: "Kettlebell Snatch",
    pattern: "olympic",
    category: "conditioning",
    equipment: ["kettlebell"],
    primary: ["glutes", "traps", "front_delts"],
    laterality: "alternating",
    contraction: "ballistic",
    metrics: ["reps", "load", "time", "rpe"],
    difficulty: 4,
    tags: ["power_endurance", "conditioning"],
  },
  {
    name: "Devil's Press",
    pattern: "olympic",
    category: "conditioning",
    equipment: ["dumbbell"],
    primary: ["full_body"],
    metrics: ["reps", "load", "time", "rpe"],
    difficulty: 4,
    tags: ["conditioning", "crossfit"],
  },
  {
    name: "Mountain Climber",
    pattern: "anti_extension",
    category: "conditioning",
    equipment: ["bodyweight"],
    primary: ["abs", "hip_flexors"],
    metrics: ["time", "reps", "rpe"],
    loadBasis: "bodyweight",
    difficulty: 1,
    tags: ["conditioning", "warmup"],
  },

  /* ============================ ISOLATION =========================== */
  {
    name: "Barbell Curl",
    pattern: "isolation",
    category: "accessory",
    equipment: ["barbell", "ez_bar"],
    primary: ["biceps"],
    secondary: ["forearms"],
    metrics: RESIST,
    difficulty: 1,
    rest: 60,
    tags: ["arms", "hypertrophy"],
  },
  {
    name: "Dumbbell Curl",
    pattern: "isolation",
    category: "accessory",
    equipment: ["dumbbell"],
    primary: ["biceps"],
    metrics: RESIST,
    difficulty: 1,
    tags: ["arms", "hypertrophy"],
  },
  {
    name: "Hammer Curl",
    pattern: "isolation",
    category: "accessory",
    equipment: ["dumbbell"],
    primary: ["biceps", "forearms"],
    metrics: RESIST,
    difficulty: 1,
    tags: ["arms", "hypertrophy"],
  },
  {
    name: "Preacher Curl",
    pattern: "isolation",
    category: "accessory",
    equipment: ["ez_bar", "bench"],
    primary: ["biceps"],
    metrics: RESIST,
    difficulty: 1,
    tags: ["arms", "hypertrophy"],
  },
  {
    name: "Incline Dumbbell Curl",
    pattern: "isolation",
    category: "accessory",
    equipment: ["dumbbell", "bench"],
    primary: ["biceps"],
    metrics: RESIST,
    difficulty: 2,
    tags: ["arms", "hypertrophy"],
  },
  {
    name: "Cable Curl",
    pattern: "isolation",
    category: "accessory",
    equipment: ["cable"],
    primary: ["biceps"],
    metrics: RESIST,
    difficulty: 1,
    tags: ["arms", "hypertrophy"],
  },
  {
    name: "Triceps Pushdown",
    pattern: "isolation",
    category: "accessory",
    equipment: ["cable"],
    primary: ["triceps"],
    metrics: RESIST,
    difficulty: 1,
    rest: 60,
    tags: ["arms", "hypertrophy"],
  },
  {
    name: "Overhead Triceps Extension",
    pattern: "isolation",
    category: "accessory",
    equipment: ["dumbbell", "cable"],
    primary: ["triceps"],
    metrics: RESIST,
    difficulty: 1,
    tags: ["arms", "hypertrophy"],
  },
  {
    name: "Skull Crusher",
    pattern: "isolation",
    category: "accessory",
    equipment: ["ez_bar", "bench"],
    primary: ["triceps"],
    metrics: RESIST,
    difficulty: 2,
    tags: ["arms", "hypertrophy"],
  },
  {
    name: "Triceps Kickback",
    pattern: "isolation",
    category: "accessory",
    equipment: ["dumbbell"],
    primary: ["triceps"],
    laterality: "unilateral",
    metrics: RESIST,
    difficulty: 1,
    tags: ["arms"],
  },
  {
    name: "Lateral Raise",
    pattern: "isolation",
    category: "accessory",
    equipment: ["dumbbell", "cable"],
    primary: ["side_delts"],
    vector: "lateral",
    metrics: RESIST,
    difficulty: 1,
    rest: 60,
    tags: ["shoulders", "hypertrophy"],
  },
  {
    name: "Front Raise",
    pattern: "isolation",
    category: "accessory",
    equipment: ["dumbbell", "plate"],
    primary: ["front_delts"],
    metrics: RESIST,
    difficulty: 1,
    tags: ["shoulders"],
  },
  {
    name: "Rear Delt Fly",
    pattern: "isolation",
    category: "accessory",
    equipment: ["dumbbell", "cable"],
    primary: ["rear_delts"],
    secondary: ["rhomboids"],
    metrics: RESIST,
    difficulty: 1,
    tags: ["shoulders", "postural"],
  },
  {
    name: "Reverse Pec Deck",
    pattern: "isolation",
    category: "accessory",
    equipment: ["machine"],
    primary: ["rear_delts"],
    metrics: RESIST,
    difficulty: 1,
    tags: ["shoulders", "postural"],
  },
  {
    name: "Barbell Shrug",
    pattern: "isolation",
    category: "accessory",
    equipment: ["barbell", "trap_bar"],
    primary: ["traps"],
    metrics: RESIST,
    difficulty: 1,
    tags: ["upper_back", "neck_health"],
  },
  {
    name: "Leg Extension",
    pattern: "isolation",
    category: "accessory",
    equipment: ["machine"],
    primary: ["quads"],
    metrics: RESIST,
    difficulty: 1,
    tags: ["hypertrophy", "rehab_friendly"],
  },
  {
    name: "Lying Leg Curl",
    pattern: "isolation",
    category: "accessory",
    equipment: ["machine"],
    primary: ["hamstrings"],
    metrics: RESIST,
    difficulty: 1,
    tags: ["hamstring", "rehab_friendly"],
  },
  {
    name: "Seated Leg Curl",
    pattern: "isolation",
    category: "accessory",
    equipment: ["machine"],
    primary: ["hamstrings"],
    metrics: RESIST,
    difficulty: 1,
    tags: ["hamstring", "rehab_friendly"],
  },
  {
    name: "Standing Calf Raise",
    pattern: "isolation",
    category: "accessory",
    equipment: ["machine", "dumbbell"],
    primary: ["calves"],
    metrics: RESIST,
    difficulty: 1,
    tags: ["lower_leg"],
  },
  {
    name: "Seated Calf Raise",
    pattern: "isolation",
    category: "accessory",
    equipment: ["machine"],
    primary: ["calves"],
    metrics: RESIST,
    difficulty: 1,
    tags: ["lower_leg", "soleus"],
  },
  {
    name: "Tibialis Raise",
    pattern: "isolation",
    category: "corrective",
    equipment: ["bodyweight", "band"],
    primary: ["tibialis"],
    metrics: RESIST,
    difficulty: 1,
    tags: ["lower_leg", "shin_health", "injury_prevention"],
  },
  {
    name: "Wrist Curl",
    pattern: "isolation",
    category: "accessory",
    equipment: ["dumbbell", "barbell"],
    primary: ["forearms"],
    metrics: RESIST,
    difficulty: 1,
    tags: ["grip"],
  },
  {
    name: "Neck Flexion",
    pattern: "isolation",
    category: "corrective",
    equipment: ["band", "plate"],
    primary: ["neck"],
    metrics: RESIST,
    difficulty: 1,
    tags: ["neck_health", "collision_sport", "injury_prevention"],
  },
  {
    name: "Neck Extension",
    pattern: "isolation",
    category: "corrective",
    equipment: ["band", "plate"],
    primary: ["neck"],
    metrics: RESIST,
    difficulty: 1,
    tags: ["neck_health", "collision_sport", "injury_prevention"],
  },

  /* ===================== MOBILITY / WARMUP / PREP ==================== */
  {
    name: "90/90 Hip Switch",
    pattern: "mobility",
    category: "mobility",
    equipment: ["bodyweight"],
    primary: ["hip_flexors", "glutes"],
    laterality: "alternating",
    metrics: MOBI,
    difficulty: 1,
    tags: ["hip_mobility", "warmup"],
  },
  {
    name: "World's Greatest Stretch",
    pattern: "mobility",
    category: "warmup",
    equipment: ["bodyweight"],
    primary: ["hip_flexors", "hamstrings"],
    secondary: ["obliques"],
    laterality: "alternating",
    metrics: MOBI,
    difficulty: 1,
    tags: ["warmup", "full_body_mobility"],
  },
  {
    name: "Couch Stretch",
    pattern: "mobility",
    category: "mobility",
    equipment: ["bodyweight"],
    primary: ["hip_flexors", "quads"],
    laterality: "unilateral",
    contraction: "isometric",
    metrics: TIMED,
    difficulty: 2,
    tags: ["hip_mobility", "cooldown"],
  },
  {
    name: "Thoracic Rotation",
    pattern: "mobility",
    category: "mobility",
    equipment: ["bodyweight"],
    primary: ["obliques"],
    laterality: "alternating",
    vector: "rotational",
    metrics: MOBI,
    difficulty: 1,
    tags: ["thoracic_mobility", "warmup"],
  },
  {
    name: "Cat-Cow",
    pattern: "mobility",
    category: "warmup",
    equipment: ["bodyweight"],
    primary: ["erectors", "abs"],
    metrics: MOBI,
    difficulty: 1,
    tags: ["spinal_mobility", "warmup"],
  },
  {
    name: "Ankle Dorsiflexion Mobilisation",
    pattern: "mobility",
    category: "mobility",
    equipment: ["band", "bodyweight"],
    primary: ["calves", "tibialis"],
    laterality: "unilateral",
    metrics: MOBI,
    difficulty: 1,
    tags: ["ankle_mobility", "squat_prep"],
  },
  {
    name: "Band Pull-Apart",
    pattern: "mobility",
    category: "warmup",
    equipment: ["band"],
    primary: ["rear_delts", "rhomboids"],
    vector: "horizontal",
    metrics: ["reps", "band_level"],
    difficulty: 1,
    tags: ["shoulder_health", "warmup", "postural"],
  },
  {
    name: "Shoulder Dislocate",
    pattern: "mobility",
    category: "warmup",
    equipment: ["band"],
    primary: ["front_delts", "rotator_cuff"],
    metrics: MOBI,
    difficulty: 1,
    tags: ["shoulder_mobility", "warmup"],
  },
  {
    name: "Scapular Wall Slide",
    pattern: "mobility",
    category: "corrective",
    equipment: ["bodyweight"],
    primary: ["traps", "serratus"],
    metrics: MOBI,
    difficulty: 1,
    tags: ["shoulder_health", "postural"],
  },
  {
    name: "Wall Angel",
    pattern: "mobility",
    category: "corrective",
    equipment: ["bodyweight"],
    primary: ["traps", "rear_delts"],
    metrics: MOBI,
    difficulty: 1,
    tags: ["postural", "thoracic_mobility"],
  },
  {
    name: "Glute Bridge March",
    pattern: "mobility",
    category: "warmup",
    equipment: ["bodyweight"],
    primary: ["glutes"],
    secondary: ["abs"],
    laterality: "alternating",
    metrics: MOBI,
    difficulty: 1,
    tags: ["activation", "warmup"],
  },
  {
    name: "Monster Walk",
    pattern: "mobility",
    category: "warmup",
    equipment: ["band"],
    primary: ["abductors", "glutes"],
    vector: "lateral",
    metrics: ["reps", "distance", "band_level"],
    difficulty: 1,
    tags: ["activation", "hip_health"],
  },
  {
    name: "Clamshell",
    pattern: "mobility",
    category: "corrective",
    equipment: ["band", "bodyweight"],
    primary: ["abductors", "glutes"],
    laterality: "unilateral",
    metrics: MOBI,
    difficulty: 1,
    tags: ["activation", "rehab_friendly"],
  },
  {
    name: "Fire Hydrant",
    pattern: "mobility",
    category: "corrective",
    equipment: ["bodyweight", "band"],
    primary: ["abductors", "glutes"],
    laterality: "unilateral",
    metrics: MOBI,
    difficulty: 1,
    tags: ["activation", "hip_health"],
  },
  {
    name: "Foam Roll Quads",
    pattern: "mobility",
    category: "mobility",
    equipment: ["foam_roller"],
    primary: ["quads"],
    metrics: TIMED,
    difficulty: 1,
    tags: ["soft_tissue", "recovery"],
  },
  {
    name: "Foam Roll T-Spine",
    pattern: "mobility",
    category: "mobility",
    equipment: ["foam_roller"],
    primary: ["erectors"],
    metrics: TIMED,
    difficulty: 1,
    tags: ["soft_tissue", "thoracic_mobility"],
  },
  {
    name: "Dynamic Leg Swing",
    pattern: "mobility",
    category: "warmup",
    equipment: ["bodyweight"],
    primary: ["hamstrings", "hip_flexors"],
    laterality: "alternating",
    metrics: MOBI,
    difficulty: 1,
    tags: ["warmup", "hip_mobility"],
  },
  {
    name: "Inchworm",
    pattern: "mobility",
    category: "warmup",
    equipment: ["bodyweight"],
    primary: ["hamstrings", "abs"],
    metrics: MOBI,
    difficulty: 1,
    tags: ["warmup", "full_body_mobility"],
  },
  {
    name: "Bear Crawl",
    pattern: "gait",
    category: "warmup",
    equipment: ["bodyweight"],
    primary: ["abs", "front_delts"],
    secondary: ["quads"],
    metrics: ["distance", "time"],
    difficulty: 2,
    tags: ["warmup", "core", "coordination"],
  },
];
